spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8080